name: Checks
on: push
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Typescript
        run: npm run ts:check

      - name: Typescript FE
        run: npm run ts:check:fe

      - name: Prettier Check
        run: npm run prettier:check
